#!/bin/bash

GITHUB_ACCOUNT_NAME=$1
GITHUB_REPO_NAME=$2
GITHUB_BRANCH_NAME=$3
GITHUB_USERNAME_AND_ACCESS_TOKEN=$4
GITHUB_REPO_URL="https://github.com/$GITHUB_ACCOUNT_NAME/$GITHUB_REPO_NAME.git"
SCRIPT_TO_RUN=$5

sudo git clone --branch $GITHUB_BRANCH_NAME --single-branch https://$GITHUB_USERNAME_AND_ACCESS_TOKEN@$GITHUB_REPO_URL
cd $GITHUB_REPO_NAME
sh $5
