#!/bin/bash

GITHUB_ACCOUNT_NAME=$1
GITHUB_REPO_NAME=$2
GITHUB_BRANCH_NAME=$3
GITHUB_USERNAME=$4
GITHUB_ACCESS_TOKEN=$5
GITHUB_REPO_URL="https://github.com/$GITHUB_ACCOUNT_NAME/$GITHUB_REPO_NAME.git"
SCRIPT_TO_RUN=$6

sudo git clone --branch $GITHUB_BRANCH_NAME --single-branch https://$GITHUB_USERNAME:$GITHUB_ACCESS_TOKEN@$GITHUB_REPO_URL
cd $GITHUB_REPO_NAME
sh $6
